-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 19:22:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estagios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estagios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estagios` DEFAULT CHARACTER SET utf8 ;
USE `estagios` ;

-- -----------------------------------------------------
-- Table `estagios`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estagios`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`area` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estagios`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `id_area` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_professor_area1_idx` (`id_area` ASC),
  CONSTRAINT `fk_professor_area1`
    FOREIGN KEY (`id_area`)
    REFERENCES `estagios`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estagios`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `id_coordenador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coordenador_curso_professor1_idx` (`id_coordenador` ASC),
  CONSTRAINT `fk_coordenador_curso_professor1`
    FOREIGN KEY (`id_coordenador`)
    REFERENCES `estagios`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estagios`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `datanasc` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `rg` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` INT NOT NULL,
  `ano_turma` CHAR(1) NOT NULL,
  `id_cidade` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aluno_cidade1_idx` (`id_cidade` ASC) ,
  INDEX `fk_aluno_curso1_idx` (`id_curso` ASC) ,
  CONSTRAINT `fk_aluno_cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `estagios`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `estagios`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estagios`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cnpj` INT(14) NOT NULL,
  `id_cidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_cidade1_idx` (`id_cidade` ASC) ,
  CONSTRAINT `fk_empresa_cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `estagios`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estagios`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`supervisor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `id_empresa` INT NOT NULL,  -- Alteração do nome da coluna
  `cargo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supervisor_empresa1_idx` (`id_empresa` ASC),  -- Alteração do nome da coluna
  CONSTRAINT `fk_supervisor_empresa1`
    FOREIGN KEY (`id_empresa`)  -- Alteração do nome da coluna
    REFERENCES `estagios`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estagios`.`estagio_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estagios`.`estagio_aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `empresa_numero_convenio` INT NOT NULL,
  `carga_horaria` INT NOT NULL,
  `id_coordenador` INT NOT NULL,
  `tipo_processo_estagio` VARCHAR(255) NOT NULL,
  `encaminhamentos` INT NOT NULL,
  `situacao_estagio` ENUM('Não Iniciado', 'Em andamento', 'Finalizado') NOT NULL,
  `data_inicio` DATE NOT NULL,
  `previsao_fim` DATE NOT NULL,
  `id_orientador` INT NOT NULL,
  `id_coorientador` INT NOT NULL,
  `supervisor` INT NOT NULL,
  `data_fim` DATE NOT NULL,
  `id_area` INT NOT NULL,
  `urlTermo_Compromisso` VARCHAR(255) NULL,
  `urlPlano_Atividades` VARCHAR(255) NULL,
  `urlAvaliacao_Empresa` VARCHAR(255) NULL,
  `urlTCC` VARCHAR(255) NULL,
  `urlAutoavaliacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estagio_aluno_aluno_idx` (`id_aluno` ASC) ,
  INDEX `fk_estagio_aluno_empresa1_idx` (`empresa_numero_convenio` ASC) ,
  INDEX `fk_estagio_aluno_professor2_idx` (`id_orientador` ASC) ,
  INDEX `fk_estagio_aluno_professor1_idx` (`id_coorientador` ASC) ,
  INDEX `fk_estagio_aluno_supervisor1_idx` (`supervisor` ASC) ,
  INDEX `fk_estagio_aluno_area1_idx` (`id_area` ASC) ,
  UNIQUE INDEX `id_coordenador_UNIQUE` (`id_coordenador` ASC),
  UNIQUE INDEX `id_aluno_UNIQUE` (`id_aluno` ASC) ,
  UNIQUE INDEX `empresa_numero_convenio_UNIQUE` (`empresa_numero_convenio` ASC) ,
  UNIQUE INDEX `id_orientador_UNIQUE` (`id_orientador` ASC),
  UNIQUE INDEX `id_coorientador_UNIQUE` (`id_coorientador` ASC) ,
  UNIQUE INDEX `supervisor_UNIQUE` (`supervisor` ASC) ,
  UNIQUE INDEX `id_area_UNIQUE` (`id_area` ASC) ,
  CONSTRAINT `fk_estagio_aluno_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `estagios`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_aluno_empresa1`
    FOREIGN KEY (`empresa_numero_convenio`)
    REFERENCES `estagios`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_aluno_coordenador_curso1`
    FOREIGN KEY (`id_coordenador`)
    REFERENCES `estagios`.`curso` (`id_coordenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_aluno_professor2`
    FOREIGN KEY (`id_orientador`)
    REFERENCES `estagios`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_aluno_professor1`
    FOREIGN KEY (`id_coorientador`)
    REFERENCES `estagios`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_aluno_supervisor1`
    FOREIGN KEY (`supervisor`)
    REFERENCES `estagios`.`supervisor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_aluno_area1`
    FOREIGN KEY (`id_area`)
    REFERENCES `estagios`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE `usuario` (
  `id` int(11) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `login` varchar(255) NOT NULL,
  `senha` varchar(255) NOT NULL
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `usuario` (`id`, `nome`, `login`, `senha`) VALUES
(1, 'admin', 'admin', 'd033e22ae348aeb5660fc2140aec35850c4da997');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
