CREATE DATABASE estagios

CREATE TABLE AREA (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL
);

CREATE TABLE CIDADE (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL
);


CREATE TABLE TERMO_COMPROMISSO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	URL VARCHAR(255) NOT NULL
);

CREATE TABLE TCC (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	URL VARCHAR(255) NOT NULL
);

CREATE TABLE AUTOAVALIACAO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	URL VARCHAR(255) NOT NULL
);

CREATE TABLE AVALIACAO_EMPRESA (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	URL VARCHAR(255) NOT NULL
);

CREATE TABLE PLANO_ATIVIDADES (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	URL VARCHAR(255) NOT NULL
);

CREATE TABLE PROFESSOR (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
ID_AREA INT NOT NULL,
	FOREIGN KEY (ID_AREA) REFERENCES AREA(ID)
);

CREATE TABLE CURSO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	ID_COORDENADOR INT NOT NULL,
	FOREIGN KEY (ID_COORDENADOR) REFERENCES PROFESSOR(ID)
);

CREATE TABLE EMPRESA (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
ENDERECO VARCHAR(255) NOT NULL,	
	TELEFONE INT NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
	CNPJ INT NOT NULL UNIQUE
);


CREATE TABLE SUPERVISOR (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	TELEFONE INT NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
	ID_EMPRESA INT NOT NULL,
CARGO VARCHAR(255) NOT NULL,
	FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);

CREATE TABLE aluno(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MATRICULA INT NOT NULL UNIQUE,
	NOME VARCHAR(255) NOT NULL,
	DATANASC DATE NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	CPF INT NOT NULL UNIQUE,
	RG VARCHAR(255) NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	TELEFONE INT NOT NULL,
	ANO_TURMA CHAR(1) NOT NULL,
	ID_CIDADE INT NOT NULL,
	ID_CURSO INT NOT NULL,
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID)
);

CREATE TABLE ESTAGIO_ALUNO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID _ALUNO INT NOT NULL UNIQUE,
ID_EMPRESA  INT NOT NULL UNIQUE,
	CARGA_HORARIA INT NOT NULL,
	ID_COORDENADOR INT NOT NULL UNIQUE,
	TIPO_PROCESSO_ESTAGIO VARCHAR(255) NOT NULL,
	NUMERO_ENCAMINHAMENTOS INT NOT NULL UNIQUE,
	SITUACAO_ESTAGIO ENUM('Não Iniciado','Em andamento','Finalizado') NOT NULL,
	DATA_INICIO DATE NOT NULL,
	PREVISAO_FIM DATENOT NULL,
	ID_ORIENTADORCOORDENADOR INT NOT NULL UNIQUE,
ID_COORIENTADOR INT NOT NULL UNIQUE,
ID_SUPERVISOR INT NOT NULL UNIQUE,
	DATA_FIM DATE,
	ID_AREA INT NOT NULL,
	ID_AVALIACAO_EMPRESA INT,
	ID_TERMO_COMPROMISSO INT,
	ID_PLANO_ATIVIDADES INT,
	ID_AUTOAVALIACAO INT,
	ID_TCC INT,
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID),
	FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID),
	FOREIGN KEY (ID_COORDENADOR) REFERENCES PROFESSOR(ID),
	FOREIGN KEY (ID_ORIENTADOR) REFERENCES PROFESSOR(ID),
	FOREIGN KEY (ID_COORIENTADOR) REFERENCES PROFESSOR(ID),
	FOREIGN KEY (ID_SUPERVISOR) REFERENCES SUPERVISOR(ID),
	FOREIGN KEY (ID_AREA) REFERENCES AREA(ID),
	FOREIGN KEY (ID_AVALIACAO_EMPREA) REFERENCES AVALIACAO_EMPRESA(ID),
	FOREIGN KEY (ID_TERMO_COMPROMISSO) REFERENCES TERMO_COMPROMISSO(ID),
	FOREIGN KEY (ID_PLANO_ATIVIDADES) REFERENCES PLANO_ATIVIDADES(ID),
	FOREIGN KEY (ID_AUTOAVALIACAO) REFERENCES AUTOAVALIACAO(ID),
    FOREIGN KEY (ID_TCC) REFERENCES TCC(ID)
);
